import type { Product, Machine, ChangeoverRule, BomItem } from '../types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-a',
    productCode: 'P-A',
    productName: '塑膠外殼',
    description: '射出成型塑膠外殼',
    defaultProcessingTime: 5,
    defaultCleaningTime: 10,
  },
  {
    id: 'prod-b',
    productCode: 'P-B',
    productName: '金屬支架',
    description: '沖壓金屬支架',
    defaultProcessingTime: 8,
    defaultCleaningTime: 15,
  },
  {
    id: 'prod-c',
    productCode: 'P-C',
    productName: '電路板',
    description: 'SMT 電路板',
    defaultProcessingTime: 12,
    defaultCleaningTime: 20,
  },
];

export const INITIAL_MACHINES: Machine[] = [
  {
    id: 'mach-1',
    machineCode: 'M-01',
    machineName: '一號射出機',
    model: 'IJ-2000',
    description: '專用塑膠外殼射出機',
    supportedProductIds: ['prod-a', 'prod-b'],
    defaultSetupTime: 20,
    defaultCleaningTime: 10,
    workingHours: {
      mon: [{ start: '08:00', end: '12:00' }, { start: '13:00', end: '17:00' }],
      tue: [{ start: '08:00', end: '12:00' }, { start: '13:00', end: '17:00' }],
      wed: [{ start: '08:00', end: '12:00' }, { start: '13:00', end: '17:00' }],
      thu: [{ start: '08:00', end: '12:00' }, { start: '13:00', end: '17:00' }],
      fri: [{ start: '08:00', end: '12:00' }, { start: '13:00', end: '17:00' }],
      sat: [],
      sun: [],
    },
    status: 'available',
    downtimes: [
      {
        id: 'dt-1',
        machineId: 'mach-1',
        type: 'maintenance',
        startTime: new Date(Date.now() + 86400000).toISOString(),
        endTime: new Date(Date.now() + 86400000 + 10800000).toISOString(),
        reason: '每月定期保養',
      },
    ],
  },
  {
    id: 'mach-2',
    machineCode: 'M-02',
    machineName: '二號多功能機',
    model: 'MF-500',
    description: '可加工全部產品類型',
    supportedProductIds: ['prod-a', 'prod-b', 'prod-c'],
    defaultSetupTime: 25,
    defaultCleaningTime: 15,
    workingHours: {
      mon: [{ start: '08:00', end: '17:00' }],
      tue: [{ start: '08:00', end: '17:00' }],
      wed: [{ start: '08:00', end: '17:00' }],
      thu: [{ start: '08:00', end: '17:00' }],
      fri: [{ start: '08:00', end: '17:00' }],
      sat: [{ start: '08:00', end: '12:00' }],
      sun: [],
    },
    status: 'available',
    downtimes: [],
  },
  {
    id: 'mach-3',
    machineCode: 'M-03',
    machineName: '三號 SMT 線',
    model: 'SMT-8',
    description: '高精密度電路板貼片線',
    supportedProductIds: ['prod-c'],
    defaultSetupTime: 30,
    defaultCleaningTime: 20,
    workingHours: {
      mon: [{ start: '08:00', end: '12:00' }, { start: '13:00', end: '17:00' }],
      tue: [{ start: '08:00', end: '12:00' }, { start: '13:00', end: '17:00' }],
      wed: [{ start: '08:00', end: '12:00' }, { start: '13:00', end: '17:00' }],
      thu: [{ start: '08:00', end: '12:00' }, { start: '13:00', end: '17:00' }],
      fri: [{ start: '08:00', end: '12:00' }, { start: '13:00', end: '17:00' }],
      sat: [],
      sun: [],
    },
    status: 'available',
    downtimes: [],
  },
];

export const INITIAL_CHANGEOVER_RULES: ChangeoverRule[] = [
  {
    id: 'rule-1',
    machineId: 'mach-1',
    fromProductId: 'prod-a',
    toProductId: 'prod-b',
    setupMinutes: 30,
    cleaningMinutes: 20,
  },
  {
    id: 'rule-2',
    machineId: 'mach-1',
    fromProductId: 'prod-b',
    toProductId: 'prod-a',
    setupMinutes: 15,
    cleaningMinutes: 10,
  },
  {
    id: 'rule-3',
    machineId: 'mach-2',
    fromProductId: 'prod-b',
    toProductId: 'prod-c',
    setupMinutes: 40,
    cleaningMinutes: 25,
  },
  {
    id: 'rule-4',
    machineId: null,
    fromProductId: 'prod-a',
    toProductId: 'prod-c',
    setupMinutes: 35,
    cleaningMinutes: 20,
  },
];

export const INITIAL_BOM_ITEMS: BomItem[] = [
  {
    id: 'bom-1',
    productId: 'prod-a',
    materialName: '塑膠粒 (ABS)',
    unit: '公斤',
    quantity: 0.12,
    customFields: { 規格: '防火級', 供應商: '奇美實業' },
  },
  {
    id: 'bom-2',
    productId: 'prod-a',
    materialName: '包裝紙盒',
    unit: '個',
    quantity: 1,
    customFields: { 規格: '單色印刷', 供應商: '榮成紙業' },
  },
  {
    id: 'bom-3',
    productId: 'prod-b',
    materialName: '不鏽鋼板 (SUS304)',
    unit: '公斤',
    quantity: 0.25,
    customFields: { 規格: '厚度 1.5mm', 供應商: '樺聯鋼鐵' },
  },
];
